# Generated by Django 4.1 on 2022-08-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='заголовок')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('male_female', models.CharField(max_length=10, verbose_name='мужские/женские')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('img', models.TextField(null=True, verbose_name='Путь до фото')),
            ],
        ),
    ]
