# Generated by Django 4.1 on 2022-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SizeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_range', models.IntegerField(choices=[(36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46')], default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='listofproduct',
            name='male_female',
        ),
        migrations.AddField(
            model_name='listofproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=7, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='listofproduct',
            name='sex',
            field=models.ManyToManyField(to='mainapp.sex', verbose_name='пол'),
        ),
        migrations.AddField(
            model_name='listofproduct',
            name='size_range',
            field=models.ManyToManyField(to='mainapp.sizerange', verbose_name='Размеры'),
        ),
    ]
