# Generated by Django 4.1 on 2022-08-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_sex_sizerange_remove_listofproduct_male_female_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizerange',
            name='size_range',
            field=models.IntegerField(default=''),
        ),
    ]
