# Generated by Django 4.1 on 2022-08-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_sizerange_size_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofproduct',
            name='img',
            field=models.TextField(default='', verbose_name='Путь до фото'),
        ),
        migrations.AlterField(
            model_name='sizerange',
            name='size_range',
            field=models.PositiveSmallIntegerField(choices=[(36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46)], default=''),
        ),
    ]
