# Generated by Django 4.1 on 2022-08-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_sizerange_size_range_sizerange_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofproduct',
            name='size_range',
        ),
        migrations.RemoveField(
            model_name='sizerange',
            name='size',
        ),
        migrations.AddField(
            model_name='listofproduct',
            name='size_range',
            field=models.ManyToManyField(to='mainapp.sizerange'),
        ),
        migrations.AddField(
            model_name='sizerange',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
