# Generated by Django 4.1 on 2022-08-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_listofproduct_size_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='mainapp.sizerange'),
        ),
        migrations.AlterField(
            model_name='listofproduct',
            name='size_range',
            field=models.ManyToManyField(to='mainapp.sizerange', verbose_name='Размеры'),
        ),
    ]
