# Generated by Django 4.1 on 2022-08-26 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_listofproduct_product_alter_listofproduct_size_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='listofproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sizerange',
            name='size',
        ),
        migrations.AddField(
            model_name='sizerange',
            name='size_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listofproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='listofproduct',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='Путь до фото'),
        ),
        migrations.RemoveField(
            model_name='listofproduct',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='listofproduct',
            name='size_range',
        ),
        migrations.AddField(
            model_name='listofproduct',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sex'),
        ),
        migrations.AddField(
            model_name='listofproduct',
            name='size_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sizerange'),
        ),
    ]
