# Generated by Django 4.1 on 2022-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_listofproduct_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.RemoveField(
            model_name='listofproduct',
            name='size_range',
        ),
        migrations.AddField(
            model_name='listofproduct',
            name='size_range',
            field=models.ManyToManyField(blank=True, to='mainapp.sizerange'),
        ),
    ]
