# Generated by Django 4.1 on 2022-09-01 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_listofproduct_price_remove_listofproduct_size_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofproduct',
            name='preview',
            field=models.CharField(blank=True, default='', max_length=230, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='listofproduct',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sex'),
        ),
        migrations.AlterField(
            model_name='listofproduct',
            name='size_range',
            field=models.ManyToManyField(blank=True, to='mainapp.sizerange'),
        ),
    ]
