# Generated by Django 4.1 on 2022-09-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_listofproduct_preview_alter_listofproduct_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizerange',
            name='size_range',
            field=models.IntegerField(blank=True, choices=[('36', '36'), ('37', '37')], null=True),
        ),
    ]
