# Generated by Django 4.1 on 2022-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_sizerange_size_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizerange',
            name='size_range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
