# Generated by Django 4.1 on 2022-10-10 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PR', 'Заказ в обработке'), ('DLV', 'Заказ в пути'), ('COM', 'Заказ завершен')], default='PR', max_length=3, verbose_name='статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('region', models.CharField(max_length=150, verbose_name='Регион')),
                ('city', models.CharField(default='', max_length=150, verbose_name='Город')),
                ('outside', models.CharField(max_length=150, verbose_name='Улица')),
                ('house', models.IntegerField(verbose_name='Дом')),
                ('apartment', models.IntegerField(default='', verbose_name='Квартира')),
                ('phone_number', models.CharField(default='', max_length=16, verbose_name='Телефон')),
                ('product', models.TextField(verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
