# Generated by Django 4.1 on 2022-09-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Размер'),
        ),
    ]
