# Generated by Django 4.1 on 2022-09-15 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_sizerange_size_range'),
        ('basket', '0004_alter_basket_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.sizerange'),
        ),
    ]
