# Generated by Django 4.1 on 2022-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_alter_basket_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Размер'),
        ),
    ]
